language: cpp
cache: ccache
deploy:
  provider: releases
  api_key:
    secure: ilkQyJbR1EK5tkXvFVerEWahiWYJsiMSG5h+bKcWh42E0FEH5gUDKqwUeu+V2uzaanvz+xuHlruVC5APw34ATARsyAvnS41u1g8RbZnuierUlOsmPati1CCBT1YzGrxSancemyZs2CjMnpu9O2JzVNWInYazPn0eq7emnbMQyV1qVgjb6v/sPFzWZnMTRZDV+oTaVvr0xH46oKEWEFZUWNlRVfrwGP/2X/69l7jCYbw14OERwS48FcBf0iatk0fEcvkeFP0HhtP9GL5Gm1fzJB5WZpg95X+K2EoXMZ4+C8T/VLqU6Vajqb6Hyi/mLzkHarmpNNmrzOEg/sjddhECF3WEK7PrlTTYQitdBw+isiem9k2dpi8hvkd+pmzGxoTqG4m+UcpSG55tQWddO4osijNtdfBh4soZjYF5DyHRlkXo0XLC+iuPtUcsbe1gG5AS88GMuG3Ggx+aAFM9almwe5j7OHy9DcN9OrpB3HOgAXxd8xSPb1ezXge7TT1dfqu+Asmmd32i9QXVJoLdq+W/VyjfCXka9z5JIP9wxaabP2xExMcOc3zn+9VJaZNR4ejjTsgFVspEzL6XDKi31JKdSZ1/LCckY5aAjSrkPfP99jzFClQDUSKIuOIO1TW7n87v69q9t9Gzcp8Vq2QJdMJ1Xa9zDPkxqpE0EnloWGrR05c=
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo add-apt-repository ppa:bitcoin/bitcoin -y
    - sudo apt-get update
    - sudo apt-get install build-essential libtool autotools-dev automake pkg-config
      libssl-dev libevent-dev bsdmainutils libboost-all-dev software-properties-common
      libdb4.8-dev libdb4.8++-dev
    script: "./autogen.sh && ./configure && make"
    before_deploy: ./prepare-for-deploy.sh false linux-x86_64 "$TRAVIS_TAG"
    env:
    - BUILD_FOR="Linux x86_64"
  - os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo add-apt-repository ppa:bitcoin/bitcoin -y
    - sudo apt-get update
    - sudo apt-get install build-essential libtool autotools-dev automake pkg-config
      libssl-dev libevent-dev bsdmainutils libboost-all-dev software-properties-common
      libdb4.8-dev libdb4.8++-dev g++-arm-linux-gnueabihf curl
    script:
    - "./autogen.sh"
    - cd depends && make HOST=arm-linux-gnueabihf -j4 && cd ..
    - "./configure --prefix=`pwd`/depends/arm-linux-gnueabihf --enable-cxx --disable-shared
      --enable-static --with-pic"
    - make
    before_deploy: ./prepare-for-deploy.sh false linux-armhf "$TRAVIS_TAG"
    env:
    - BUILD_FOR="Linux armhf"
  - os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo add-apt-repository ppa:bitcoin/bitcoin -y
    - sudo apt-get update
    - sudo apt-get install build-essential libtool autotools-dev automake pkg-config
      libssl-dev libevent-dev bsdmainutils g++-mingw-w64-i686 mingw-w64-i686-dev g++-mingw-w64-x86-64
      mingw-w64-x86-64-dev curl libboost-system-dev libboost-filesystem-dev libboost-chrono-dev
      libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb4.8-dev
      libdb4.8++-dev
    script:
    - "./autogen.sh"
    - cd depends && make HOST=x86_64-w64-mingw32 -j4 && cd ..
    - "./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 --enable-cxx --disable-shared
      --enable-static --with-pic"
    - make
    before_deploy: ./prepare-for-deploy.sh true windows-x86_64 "$TRAVIS_TAG"
    env:
    - BUILD_FOR="Windows x86_64"
  - os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo add-apt-repository ppa:bitcoin/bitcoin -y
    - sudo apt-get update
    - sudo apt-get install build-essential libtool autotools-dev automake pkg-config
      libssl-dev libevent-dev bsdmainutils g++-mingw-w64-i686 mingw-w64-i686-dev g++-mingw-w64-x86-64
      mingw-w64-x86-64-dev curl libboost-system-dev libboost-filesystem-dev libboost-chrono-dev
      libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb4.8-dev
      libdb4.8++-dev
    script:
    - "./autogen.sh"
    - cd depends && make HOST=i686-w64-mingw32 -j4 && cd ..
    - "./configure --prefix=`pwd`/depends/i686-w64-mingw32 --enable-cxx --disable-shared
      --enable-static --with-pic"
    - make
    before_deploy: ./prepare-for-deploy.sh true windows-x86 "$TRAVIS_TAG"
    env:
    - BUILD_FOR="Windows x86"
  - os: osx
    before_install:
    - brew install autoconf automake berkeley-db4 libtool boost openssl pkg-config ccache rename || true
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - rename -e 's/.dylib/.dylib.hidden/' /usr/local/opt/boost/lib/*.dylib
    - rename -e 's/.dylib/.dylib.hidden/' /usr/local/opt/berkeley-db@4/lib/*.dylib
    - rename -e 's/.dylib/.dylib.hidden/' /usr/local/opt/openssl/lib/*.dylib
    - EDITOR="./mac-openssl-fix.py" brew edit openssl
    - brew install openssl --force
    script:
    - export LDFLAGS=-L/usr/local/opt/openssl/lib
    - export CPPFLAGS=-I/usr/local/opt/openssl/include
    - "./autogen.sh"
    - "./configure --with-gui=no --with-libs=no --with-miniupnpc=no"
    - make
    before_deploy: ./prepare-for-deploy.sh false mac "$TRAVIS_TAG"
    env:
    - BUILD_FOR=Mac
